/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package financemanagement;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author B.Traders
 */
class Node{
        int data,data1,data2,data3;
                int data4;
        Node next;
        Node(){
            data=0;
            data1=0;
            data2=0;
            data3=0;
            data4=0;
            next=null;
        }
        Node(int a,int b,int c,int d,int e,Node n){
            data=a;
            data1=b;
            data2=c;
            data3=d;
            data4=a+b+c+d;
            next=n;
        }
        public void setData(int a,int b,int c,int d,int e){
            data=a;
            data1=b;
            data2=c;
            data3=d;
            data4=a+b+c+d;
        }
        public void setNext(Node n){
            next=n;
        }
        public int getData(){
            return (data);
        }
        public Node getNext(){
            return (next);
        }
    }

class LinkedList{
    int size;
    Node start;
    int a,b,c,d;
    
    int e;
    LinkedList(){
        size=0;
        start=null;
    }

public void InsertAtFirst(int a,int b,int c,int d,int e){
this.a=a;
this.b=b;
this.c=c;
this.d=d;
this.e=e;
e=a+b+c+d;
Node n=new Node();
n.setData(a,b,c,d,e);
n.setNext(start);
start=n;
size++;
}
public void InsertAtLast(int a,int b,int c,int d){
this.a=a;
this.b=b;
this.c=c;
this.d=d;
Node n=new Node();
n.setData(a,b,c,d,e);
n.setNext(start);
Node t;
t=start;
if(t==null){
    start=n;
}
else{
    while(t.getNext()!=null){
    t=t.getNext();
}
    t.setNext(n);
}
size++;
}
public void InsertAtSpecific(int a,int b,int c,int d,int e,int pos){
    
    this.a=a;
this.b=b;
this.c=c;
this.d=d;
if(pos==1){
    InsertAtFirst(a,b,c,d,e);
}
else if(pos==size+1){
    InsertAtLast(a,b,c,d);
}
else if(pos>1 && pos<=size){
    Node n,t;
    t=start;
    n=new Node(a,b,c,d,e,null);
    for(int i=0;i<pos-1;i++){
        t.getNext();
        
    }
    n.setNext(t.getNext());
    t.setNext(n);
    size++;
}
else{
    System.out.println("Insertion not possible");
}
}
public void DeleteAtFirst(){
    if(start==null){
        System.out.println("List is empty");
    }
    else{
        start=start.getNext();
        size--;
    }
}
public void DeleteAtLast(){
    if(start==null){
        System.out.println("List is empty");
    }
    else if(size==1){
        start=null;
        size--;
    }
    else{
        Node t;
        t=start;
        for(int i=0;i<size-1;i++){
            t.getNext();
            t.setNext(null);
            size--;
        }
    }
}
public void DeleteAtSpecific(int pos){
    if(start==null){
        System.out.println("List is empty");
    }
    else if(pos<1 || pos>size){
        System.out.println("Invalid position");
    }
    else if(pos==1){
        DeleteAtFirst();
    }
    else if(pos==size){
        DeleteAtLast();
    }
    else{
        Node t;
        t=start;
        Node ta=new Node();
        for(int i=1;i<pos-1;i++){
            t.getNext();
            ta=t.getNext();
            t.setNext(ta.getNext());
            size--;
           }
    }
}
boolean IsEmpty(){
    if(start==null){
        return (true);
    }
    else{
        return (false);
    }
}
public void Display(){
    if(IsEmpty()){
        System.out.println("List is vacant");
    }
    else{
    Node ptr;
    ptr=start;
    for(int i=0;i<=size;i++){
        System.out.println(" "+ptr.getData());
        ptr.getNext();
    }
}
}
}

public class main extends javax.swing.JFrame {
public static int change=0,c;   
public static LinkedList bat = new LinkedList();
    public static DefaultTableModel j;
int count=0;
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Food", "Education", "Rent", "Clothing", "Total Expenses"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(320, 340, 530, 240);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Clothing");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 540, 100, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Food");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 390, 60, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Education");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 440, 110, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Rent");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 490, 60, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(180, 540, 130, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(180, 390, 130, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(180, 440, 130, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(180, 490, 130, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(470, 610, 130, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Enter your Expenses Here");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 280, 320, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(50, 610, 130, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Show Data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(50, 670, 130, 40);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(690, 610, 130, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Enter index to delete & Update");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(520, 660, 250, 20);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(590, 690, 110, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/financemanagement/financial-chartman.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 270, 860, 470);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PERSONAL FINANCE MANAGEMENT SYSTEM");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(200, 30, 510, 29);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Enter your Salary");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(320, 80, 210, 20);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(300, 130, 250, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("Future Financial Status");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(270, 190, 300, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/financemanagement/wp6599038.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1, 6, 850, 260);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Back");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Close");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         String a=jTextField1.getText();
     String b=jTextField2.getText();
     String c=jTextField3.getText();
     String d=jTextField4.getText();
  
     int ia=Integer.parseInt(a);
     int ja=Integer.parseInt(b);
     int ka=Integer.parseInt(c);
     int la=Integer.parseInt(d);
     count=ia+ja+ka+la;
     System.out.println(count);
        j = new DefaultTableModel();
      j=(DefaultTableModel)jTable1.getModel(); 
      bat.InsertAtFirst(ia, ja, ka,la,count);
      JOptionPane.showMessageDialog(this,"Data Added");
      System.out.println(bat.a+" "+bat.b+" "+bat.c+" "+bat.d+" "+bat.e);      
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{          
      Node n1;
      n1=bat.start;
       
    for(int i=0;i<bat.size;i++){
        jTable1.setValueAt(n1.data, i, 0);
        jTable1.setValueAt(n1.data1, i, 1);
        jTable1.setValueAt(n1.data2, i, 2);
        jTable1.setValueAt(n1.data3, i, 3);
        jTable1.setValueAt(n1.data4, i, 4);
        
       n1=n1.getNext();
       
    }                                        
    }catch(Exception e){}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
                  String a=jTextField1.getText();
     String b=jTextField2.getText();
     String c=jTextField3.getText();
     String d=jTextField4.getText();
       String n=jTextField5.getText();
           int ia=Integer.parseInt(a);
     int ja=Integer.parseInt(b);
     int ka=Integer.parseInt(c);
     int la=Integer.parseInt(d);
       int n1=Integer.parseInt(n);
        bat.InsertAtSpecific(ia,ja,ka,la,count,n1-1);
        
        jTable1.setValueAt(bat.a,n1,0);
        jTable1.setValueAt(bat.b,n1,1);
        jTable1.setValueAt(bat.c,n1,2);
        jTable1.setValueAt(bat.d,n1,3);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                String z=jTextField5.getText();
       int n1=Integer.parseInt(z);
        bat.DeleteAtSpecific(n1);
       j.removeRow(n1);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String a=jTextField6.getText();
        int i=Integer.parseInt(a);
       if(i > count){
          JOptionPane.showMessageDialog(this,"You Future Financial Status is Strong");
       }
      else if(i < count){
          JOptionPane.showMessageDialog(this,"You Future Financial Status is Weak");
       } 
      else if(i== count){
          JOptionPane.showMessageDialog(this,"You Future Financial Status is Balanced");
       } 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        main m=new main();
        m.setVisible(false);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        login l=new login();
            
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
